src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $ArticleTitle = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $ArticleContent = null;

    #[ORM\OneToMany(targetEntity: Media::class, mappedBy: 'article')]
    private Collection $medias;

    public function __construct()
    {
        $this->medias = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArticleTitle(): ?string
    {
        return $this->ArticleTitle;
    }

    public function setArticleTitle(string $ArticleTitle): static
    {
        $this->ArticleTitle = $ArticleTitle;

        return $this;
    }

    public function getArticleContent(): ?string
    {
        return $this->ArticleContent;
    }

    public function setArticleContent(string $ArticleContent): static
    {
        $this->ArticleContent = $ArticleContent;

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedias(): Collection
    {
        return $this->medias;
    }

    public function addMedia(Media $media): static
    {
        if (!$this->medias->contains($media)) {
            $this->medias->add($media);
            $media->setArticle($this);
        }

        return $this;
    }

    public function removeMedia(Media $media): static
    {
        if ($this->medias->removeElement($media)) {
            // set the owning side to null (unless already changed)
            if ($media->getArticle() === $this) {
                $media->setArticle(null);
            }
        }

        return $this;
    }

    
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Media;
use App\Form\ArticleType;
use App\Form\MediaType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class BlogController extends AbstractController
{
    
    #[Route('admin/blog', name: 'admin_blog')]
    public function index(ArticleRepository $repo): Response
    {
        //recuperer les articles presents en base de donner
        $articles = $repo->findAll();

        return $this->render('blog/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    #[Route('/blog', name: 'blog')]
    public function blog(ArticleRepository $repo): Response
    {
        //recuperer les articles presents en base de donner
        $articles = $repo->findAll();

        return $this->render('blog/articles_blog.html.twig', [
            'articles' => $articles,
        ]);
    }

    //Affichage et lecture d'un article
    #[Route('/article/{id}', name: 'article_show')]
    public function article(Article $article):Response
    {
    return $this->render('blog/article_show.html.twig',['article'=>$article]);
    
    }

    // Ajout et modification des articles
    #[Route('/new', name: 'admin_article_new')]
    #[Route('/update/{id}', name: 'admin_article_update')]
    public function new(Request $request, EntityManagerInterface $manager, $id = null): Response
    {
        if (!$id) {
            // si pas de articles selectionnée, ou inexistante j'en crée
            $article = new Article();
        } else {
            // on a un id donc on recupere l'objet , la article dans le repository via son id
            $article = $manager->getRepository(Article::class)->find($id);
        }
        // formulaire articlesType 
        $form = $this->createForm(ArticleType::class, $article);

        //gestion requete
        $form->handleRequest($request);

        // verification si formulaire soumis et si il est valide
        if ($form->isSubmitted() && $form->isValid()) {

            //on recupere les valeurs du form
            //on crée une instance de la classe articles , qui recupere les valeurs
            $article = $form->getData();

            // on persiste les valeurs et on execute la requete
            $manager->persist($article);
            $manager->flush();

            // //redirection à l'ajout de media
            return $this->redirectToRoute('admin_article_add_media', ['id' => $article->getId()]); //renvoyer l'id de la article dans l'url de media create);
        }

        return $this->render('blog/new_article.html.twig', ['form' => $form->createView()]);
    }




    //Rajouter  media à un article
    #[Route('/admin/article/{id}', name: 'admin_article_add_media')]
    public function addMedia(Request $request, EntityManagerInterface $manager, Article $article): Response
    {
        // Crée un nouveau média
        $media = new Media();
        // Crée le formulaire pour le média
        $form = $this->createForm(MediaType::class, $media);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Récupère le fichier média
            $file = $form->get('src')->getData();
            // Génère un nom de fichier à partir du titre de l'article
            $fileName = $article->getId() . '.' . $file->guessExtension();
            // Déplace le fichier vers le dossier d'upload
            $file->move(
                $this->getParameter('upload_dir'),
                $fileName
            );

            // Associe le fichier média à la article
            $media->setSrc($fileName);
            $article->addMedia($media); // rajouter le media à l'article

            // Persiste le média
            $manager->persist($media);
            $manager->flush();

            // // Redirige vers la page de gestion des articles
            return $this->redirectToRoute('admin_blog');
            // return $this->redirectToRoute('article_detail', ['id' => $article->getId()]);
        }

        // Rend le formulaire pour ajouter un média
        return $this->render('blog/add_media.html.twig', [
            'form' => $form->createView(),
            'article' => $article,
        ]);
    }

    #[Route('admin/detail/{id}', name: 'admin_detail_article')]
    public function detail(Article $article, EntityManagerInterface $manager): Response
    {
        // dd($article);
        return $this->render('blog/detail_article.html.twig', ['article' => $article]);
    }
    //Supprimer un article 
    #[Route('/delete/{id}', name: 'admin_article_delete')]
    public function delete(ArticleRepository $repo, EntityManagerInterface $manager, $id): Response
    {
        $article = $repo->find($id);
        $medias = $article->getMedias(); // avec les medias du parfum
        //faire un for each pour les media les unlink et supprimer

        foreach ($medias as $media) {

            unlink($this->getParameter('upload_dir') . '/' . $media->getSrc());
            $manager->remove($media); //supprime les medias
        }
        $manager->remove($article); // supprimer l'article
        $manager->flush();

        return $this->redirectToRoute('admin_blog');
    }

    //Supprimer le medias d'une article
    #[Route('/admin/article/{id}', name: 'admin_article_delete_media')]
    public function deleteMedia(EntityManagerInterface $manager, ArticleRepository $repo, $id): Response
    {
        $article = $repo->find($id);
        // Récupère le média associé à la article
        $media = $article->getMedias();
      

        // if ($media !== null) {
        //     // Supprime le fichier physique du système de fichiers
        //     $fileName = $media->getSrc();
        //     $filePath = $this->getParameter('upload_dir') . '/' . $fileName;
        //     if (file_exists($filePath)) {
        //         unlink($filePath);
        //     }

        //     // Supprime le média de la base de données
        //     $manager->remove($media);
        //     $manager->flush();
        // }

        // Redirige vers la page de gestion des article
        return $this->redirectToRoute('admin_blog');
    }
}

templates/blog/add_media.html.twig
{% extends 'backoffice.html.twig'  %}

{% block body %}
<div class="container-fluid p-3">
    {{form(form)}}
 </div>
{% endblock %}

templates/blog/article_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Article : {{ article.ArticleTitle }}
{% endblock %}

{% block body %}
<div class="article-detail d-flex flex-column">
  {% if article.medias is not empty %}
    <img src="{{ asset('upload/' ~ article.medias[0].src) }}" class="img-fluid w-100 article-cover-image" style="height: 200px; object-fit: cover;" alt="Image de couverture de l'article : {{ article.ArticleTitle }}">
  {% endif %}

  <div class="article-content container mt-4"> <div class="row">
      <div class="col-md-10 mx-auto">
        <h1>{{ article.ArticleTitle }}</h1>
        <p class="article-content">{{ article.ArticleContent | raw }}</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/blog/articles_blog.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    Blog: Découvrez nos articles
{% endblock %}
{% block body %}

    <div class="container-fluid d-flex flex-column">
        <div class="container ">
            <h1 class="text-center mb-4">Blog : Découvrez nos articles</h1>
            <article>
                <p>Bienvenue dans notre section blog dédiée à l'univers captivant des parfums ! 
                    Que vous soyez un passionné de longue date ou un néophyte curieux, notre plateforme est conçue pour vous éclairer, vous inspirer et vous guider à travers les méandres envoûtants de cet art olfactif..
                    Que vous cherchiez à comprendre les subtilités des différentes familles olfactives, à découvrir les dernières tendances du monde du parfum ou à trouver le parfum parfait pour chaque occasion, notre blog est votre compagnon idéal.</p>
            </article>
            <div class="row row-cols-1">
                {% for article in articles %}
                    <div class="mb-4 mt-5">
                        <div class="border rounded overflow-hidden shadow-sm position-relative">
                            <div class="row g-0">
                                <div class="col-md-4">
                                    {% if article.medias is not empty %}
                                        <img src="{{ asset('upload/' ~ article.medias[0].src) }}" class="img-fluid" alt="Image de couverture de l'article : {{ article.ArticleTitle }}">
                                    {% endif %}
                                </div>
                                <div class="col-md-8">
                                    <div class="p-4">
                                        <h5 class="mb-3">{{ article.ArticleTitle }}</h5>
                                        <p class="card-text">{{ article.ArticleContent|striptags|slice(0, 150) ~ '...' }}</p>
                                        <a href="{{ path('article_show', {'id': article.id}) }}" class="btn btn-turquois">Lire la suite</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <footer class="mt-auto"> <!-- Utilisation de la classe "mt-auto" pour placer le footer en bas -->
            <!-- Contenu du footer -->
        </footer>
    </div>

{% endblock %}

templates/blog/detail_article.html.twig
{% extends 'backoffice.html.twig' %}

{% block title %}Détail de l'article - {{ article.articleTitle }}{% endblock %}

{% block body %}

<div class="container mt-4">
  <div class="row">
    <div class="col-md-8">
      <h2>{{ article.articleTitle }}</h2>
      <p>{{ article.articleContent | raw }}</p>
    </div>
    <div class="col-md-4">
      {% if article.medias is not empty %}
        <h4>Médias associés</h4>
        <div class="d-flex flex-wrap gap-2">
          {% for media in article.medias %}
            <div class="img-thumbnail">
              <img src="{{ asset('upload/' ~ media.src) }}" alt="image couverture d el'article : {{ article.articleTitle }}" class="img-fluid">
              <a href="{{ path('admin_article_delete_media', {'id': article.id, 'mediaId': media.id}) }}" class="btn btn-sm btn-danger">Supprimer</a>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <p>Aucun média associé à cet article.</p>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

templates/blog/index.html.twig
{% extends 'backoffice.html.twig' %}

{% block title %} Gestion articles 
{% endblock %}

{% block body %}

	<div class="container-fluid p-5">
		<h1>Gestion des articles du blog</h1>

		<a href="{{ path('admin_article_new')}}" class="btn btn-turquois w-25 mr-3">Ajouter un article</a>

		<table class="table">
			<thead>
				<tr>
					<th scope="col">Id</th>
					<th scope="col">Nom</th>
					<th scope="col">Contenu</th>

				</tr>
			</thead>
			<tbody>
				{% if articles | length > 0 %}
					{% for article in articles %}
						<tr>
							<th scope="row"><p>{{article.id}}</th>
							<td>
								{{article.articleTitle}}
							</td>
							<td><p class="card-text">{{ article.ArticleContent|striptags|slice(0, 150) ~ '...' }}</p>
							
							</td>

							<td>
								<a href="{{ url("admin_article_update", {'id' : article.id}) }}" class="btn btn-turquois">Modifier</a>
							</td>
							<td>
								<a href=" {{ url('admin_article_delete', {'id' : article.id}) }}" class="btn btn-bronze ">Supprimer</a>
							</td>
							<td>
								<a href=" {{ url('admin_detail_article', {'id' : article.id}) }}" class="btn btn-cream ">Detail</a>
							</td>
						{% endfor %}
					{% endif %}

				</div>

			</tbody>
		{% endblock %}

templates/blog/new_article.html.twig
{% extends 'backoffice.html.twig'  %}

{% block body %}
	<div
		class="container-fluid p-3" id="creationArticle">
		{# {{form(form)}} #}

		{{ form_start(form) }}
		{{  form_row(form.ArticleTitle) }}
		{# {{  form_row(form.articleContent) }}est hidden type#}

		<p>Contenu de l'article</p>
		<div id="editor"></div>


		{{ form_end(form) }}
	</div>
{% endblock %}

{% block javascripts %}

{{parent()}}
	{#<script src="{{ asset('ckeditor5/ckeditor.js')}}"></script>#}
	<script src="{{ asset('js/ckeditorInit.js')}}" defer></script>
{% endblock %}