src/Entity/Perfume.php
<?php

namespace App\Entity;

use App\Repository\PerfumeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PerfumeRepository::class)]
class Perfume
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $perfume_title = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $gender = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'perfumes')]
    private ?OlfactiveFamily $olfactive_family_id = null;

    #[ORM\ManyToMany(targetEntity: Notes::class, inversedBy: 'perfumes')]
    private Collection $note_id;

    #[ORM\OneToMany(targetEntity: Media::class, mappedBy: 'perfume')]
    private Collection $medias_id;

    #[ORM\OneToMany(targetEntity: Purchase::class, mappedBy: 'perfume')]
    private Collection $purchase;

    #[ORM\ManyToMany(targetEntity: Favorites::class, mappedBy: 'perfume_id')]
    private Collection $favorites;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $volume = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $quantity = null;

    #[ORM\Column(length: 255)]
    private ?string $brand = null;

    public function __construct()
    {
        $this->note_id = new ArrayCollection();
        $this->medias_id = new ArrayCollection();
        $this->purchase = new ArrayCollection();
        $this->favorites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPerfumeTitle(): ?string
    {
        return $this->perfume_title;
    }

    public function setPerfumeTitle(string $perfume_title): static
    {
        $this->perfume_title = $perfume_title;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getOlfactiveFamilyId(): ?OlfactiveFamily
    {
        return $this->olfactive_family_id;
    }

    public function setOlfactiveFamilyId(?OlfactiveFamily $olfactive_family_id): static
    {
        $this->olfactive_family_id = $olfactive_family_id;

        return $this;
    }

    /**
     * @return Collection<int, Notes>
     */
    public function getNoteId(): Collection
    {
        return $this->note_id;
    }

    public function addNoteId(Notes $noteId): static
    {
        if (!$this->note_id->contains($noteId)) {
            $this->note_id->add($noteId);
        }

        return $this;
    }

    public function removeNoteId(Notes $noteId): static
    {
        $this->note_id->removeElement($noteId);

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMediasId(): Collection
    {
        return $this->medias_id;
    }

    public function addMediasId(Media $mediasId): static
    {
        if (!$this->medias_id->contains($mediasId)) {
            $this->medias_id->add($mediasId);
            $mediasId->setPerfume($this);
        }

        return $this;
    }

    public function removeMediasId(Media $mediasId): static
    {
        if ($this->medias_id->removeElement($mediasId)) {
            // set the owning side to null (unless already changed)
            if ($mediasId->getPerfume() === $this) {
                $mediasId->setPerfume(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Purchase>
     */
    public function getPurchase(): Collection
    {
        return $this->purchase;
    }

    public function addPurchase(Purchase $purchase): static
    {
        if (!$this->purchase->contains($purchase)) {
            $this->purchase->add($purchase);
            $purchase->setPerfume($this);
        }

        return $this;
    }

    public function removePurchase(Purchase $purchase): static
    {
        if ($this->purchase->removeElement($purchase)) {
            // set the owning side to null (unless already changed)
            if ($purchase->getPerfume() === $this) {
                $purchase->setPerfume(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Favorites>
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorites $favorite): static
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites->add($favorite);
            $favorite->addPerfumeId($this);
        }

        return $this;
    }

    public function removeFavorite(Favorites $favorite): static
    {
        if ($this->favorites->removeElement($favorite)) {
            $favorite->removePerfumeId($this);
        }

        return $this;
    }

    public function getVolume(): ?int
    {
        return $this->volume;
    }

    public function setVolume(int $volume): static
    {
        $this->volume = $volume;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): static
    {
        $this->brand = $brand;

        return $this;
    }

    public function __toString()
    {
        return $this->id;
    }
}

src/Controller/CatalogueController.php
<?php

namespace App\Controller;

use App\Entity\Notes;
use App\Entity\OlfactiveFamily;
use App\Entity\Perfume;
use App\Repository\NotesRepository;
use App\Repository\OlfactiveFamilyRepository;
use App\Repository\PerfumeRepository;
use Doctrine\ORM\Mapping\Id;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;


#[Route('/catalogue')]
class CatalogueController extends AbstractController
{
    #[Route('/', name: 'app_catalogue')]
    public function index(PerfumeRepository $repo, OlfactiveFamilyRepository $familyRepo, NotesRepository $notesRepo, Request $request): Response
    {
// //recupere le choix d efam olf du user
//         $olfactiveFamily = $request->request->get('olfactiveFamily');

//         if(!empty($olfactiveFamily)){
//             $filteredPerfumes = $repo->findByOLf($olfactiveFamily);
//         }

        $perfumes = $repo->findAll();
        $families= $familyRepo->findAll();
        $notes= $notesRepo->findAll();
        return $this->render('catalogue/index.html.twig', [
            'perfumes' => $perfumes,
            'families'=>$families,
            'notes'=>$notes
        ]);
    }

    

    // #[Route('/filter', name: 'app_catalogue_filter', methods: ['POST'])]
    // public function filter(Request $request, PerfumeRepository $perfumeRepository): Response
    // {
    //     $olfactiveFamily = $request->request->get('olfactiveFamily');
    //     $brand = $request->request->get('brand');
    //     $priceRange = $request->request->get('priceRange');
    //     $noteId = $request->request->get('note');

    //     if(!empty($olfactiveFamily) || !empty($brand) || !empty($priceRange))
    //     {
    //         $filteredIds = $perfumeRepository->findByFilters((int)$olfactiveFamily, $brand, $priceRange, null);
    //         $filteredPerfumes = [];
            
    //         foreach ($filteredIds as $id) {
                
    //             # code...
    //             $perfume = $perfumeRepository->find($id);
    //             array_push($filteredPerfumes, $perfume);
    //         }
    //         dump($filteredPerfumes);
    
    //     }


    //     // var_dump($perfumeRepository->findByFilters($olfactiveFamily, $brand,$priceRange,null));
    //     // die;
    //     // Appliquer les filtres en fonction des paramètres
    //     // if ($olfactiveFamily && !$brand && !$priceRange && !$noteId) {
    //     //     // Filtrage par famille olfactive uniquement
    //     //     $filteredPerfumes = $perfumeRepository->findByOlfactiveFamily($olfactiveFamily);
    //     // } elseif (!$olfactiveFamily && $brand && !$priceRange && !$noteId) {
    //     //     // Filtrage par marque uniquement
    //     //     $filteredPerfumes = $perfumeRepository->findByBrand($brand);
    //     // } elseif (!$olfactiveFamily && !$brand && $priceRange && !$noteId) {
    //     //     // Filtrage par gamme de prix uniquement
    //     //     $filteredPerfumes = $perfumeRepository->findByPriceRange($priceRange);
    //     // } elseif (!$olfactiveFamily && !$brand && !$priceRange && $noteId) {
    //     //     // Filtrage par note uniquement
    //     //     $filteredPerfumes = $perfumeRepository->findByNoteId($noteId);
    //     // } elseif ($olfactiveFamily && $brand && !$priceRange && !$noteId) {
    //     //     // Filtrage par famille olfactive et marque
    //     //     $filteredPerfumes = $perfumeRepository->findByOlfactiveFamilyAndBrand($olfactiveFamily, $brand);
    //     // } 
    //     //elseif (...) {
    //         // Ajoutez d'autres conditions de filtrage au besoin...
    //     //}
    //      else {
    //         // Aucun filtre appliqué, récupérer tous les parfums
    //         $filteredPerfumes = $perfumeRepository->findAll();
    //     }

        
    //     return $this->redirectToRoute('app_catalogue', [
    //         'perfumes' => $filteredPerfumes,
    //         'selectedOlfactiveFamilyId' => $olfactiveFamily // Optionnel : utile pour garder la sélection dans le menu déroulant
    //     ]);
    // }
    



    //aller à la page qui affiche le detail du produit
    #[Route('/show-perfume/{id}', name: 'app_show_perfume')]
    public function show(PerfumeRepository $repo, $id):Response
    {
    //je recupere l'id du parfum clické et je vais à son detail
    $perfume = $repo->find($id);
    
    return $this->render('catalogue/show_perfume.html.twig',['perfume'=>$perfume]);
    
    }
}

templates/catalogue/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Catalogue Perfumes {% endblock %}
{% block body %}
<div class="container-fluid py-5">
   <div class="row justify-content-center">
    <div class="col-md-6">
        <!-- Form filtres -->
        <form action="{# {{ path('app_catalogue_filter') }} #}" method="POST" class="mb-4">
            <div class="input-group align-items-start">
                <select name="olfactiveFamily" class="form-select mb-3" aria-label="Filtrer par famille olfactive">
                    <option value="">Filtrer par famille olfactive</option>
                    {% for family in families %}
                        <option value="{{ family.id }}">{{ family.familyName }}</option>
                    {% endfor %}
                </select>
                <input type="text" name="brand" class="form-control mb-3" placeholder="Filtrer par marque">
                <select name="priceRange" class="form-select mb-3" aria-label="Filtrer par prix">
                    <option value="">Filtrer par prix</option>
                    <option value="0-50">0 - 50</option>
                    <option value="50-100">50 - 100</option>
                    <option value="100-200">100 - 200</option>
                    <option value="200+">200 et plus</option>
                </select>
                <select name="note" class="form-select mb-3" aria-label="Filtrer par note">
                    <option value="">Filtrer par note</option>
                    {% for note in notes %}
                        <option value="{{ note.id }}">{{ note.noteName }}</option>
                    {% endfor %}
                </select>
                <button class="btn btn-turquois mb-3" type="submit">Filtrer</button>
            </div>
        </form>
    </div>
</div>

</div>

{# Catalogue #}
<div class="container ">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4  ">
        {% for perfume in perfumes %}
            <div class="col my-4">
                <a href="{{ path('app_show_perfume', {'id' : perfume.id}) }}" class="text-decoration-none text-dark">
                    <div class="card h-100">
                        {% if perfume.mediasId | length > 0 %}
                            <div style="position: relative; width: 100%; padding-top: 100%;">
                                <img src="{{ asset('upload/' ~ perfume.mediasId[0].src) }}" class="card-img-top img-fluid position-absolute top-0 start-0 w-100 h-100" style="object-fit: cover;" alt="{{ perfume.perfumeTitle }}">
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ perfume.perfumeTitle }}</h5>
                            <p class="card-text">Famille olfactive: {{ perfume.olfactiveFamilyId.familyName }}</p>
                            <p class="card-text">{{ perfume.brand }}</p>
                            <p class="card-text">{{ perfume.volume }} ml</p>
                            <p class="card-text">{{ perfume.price }}€</p>
                            <a href="{{ path('add_to_cart', {'id': perfume.id}) }}" class="btn btn-turquois">Ajouter au panier</a>
                            <a href="#" class="btn btn-link">
                                {# à lier au rajout aux favoris #}
                                <i class="fa-regular fa-heart text-muted"></i>
                            </a>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/catalogue/show_perfume.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail Parfum : {{perfume.perfumeTitle}}{% endblock %}

{% block body %}
    <!-- Parfum section -->
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <!-- Parfum image col -->
                <div class="col-md-6">
                    <div class="ratio ratio-1x1 mb-5 mb-md-0">
                        <img src="{{ asset('upload/' ~ perfume.mediasId[0].src) }}" class="card-img-top w-100 h-100 object-cover" alt="Image du parfum : {{ perfume.perfumeTitle }}">
                    </div>
                </div>
                <!-- Parfum details col -->
                <div class="col-md-6">
                    <div class="small mb-1">Ref: {{ perfume.id }}</div>
                    <h1 class="display-5 fw-bolder">{{ perfume.perfumeTitle }}</h1>
                    <div class="fs-5 mb-5">
                        <p><b>Prix:</b> {{ perfume.price }}€</p>
                        <p><b>Volume:</b> {{ perfume.volume }}ml</p>
                        <p><b>Famille olfactive:</b> {{ perfume.olfactiveFamilyId.familyName }}</p>
                        <p><b>Marque:</b> {{ perfume.brand }}</p>
                    </div>
                    <div>
                        <p class="lead">{{ perfume.description }}</p>
                    </div>
                    <div class="d-flex mt-3">
                        <a class="btn btn-turquois" href="{{ path('add_to_cart', {'id': perfume.id}) }}">
                            <i class="bi-cart-fill me-1"></i>
                            Ajouter au panier
                        </a>
                    </div>
                </div>
            </div>
            <!-- Parfum notes carousel -->
            <div class="row mt-5">
                <div class="col-md-6">
                    <h2 class="fw-bolder mb-4">Notes:</h2>
                    <div id="noteCarousel" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            {% for note in perfume.noteId %}
                                <div class="carousel-item {% if loop.first %}active{% endif %}">
                                    <div class="card">
                                        <img src="{{ asset('upload/' ~ note.media.src) }}" class="card-img-top img-fluid" style="height: 200px; object-fit: cover;" alt="{{ note.noteName }}">
                                        <div class="card-body">
                                            <p class="card-text">{{ note.noteName }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#noteCarousel" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#noteCarousel" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>

<!--Produits similaires -->
    <section class="py-5 bg-light">
        <div class="container px-4 px-lg-5 mt-5">
            <h2 class="fw-bolder mb-4">Produits similaires</h2>
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                
            </div>
        </div>
    </section>
{% endblock %}